### ISSUE TITLE
cannot connect because server is full

### ISSUE THREAD

**Issue by fred0r** [ShadowsAdi/AdvancedSlotReservation#2]
started server with `+maxplayers 25` and one also hltv is connecting.
overall i want that 24 players can connect and play, but when 24 players (+hltv) are connected, i cant connect as admin - it says: server full.
admin-users are added to `users.ini` only and authenticate only via steamid.
what am i doing wrong?

**Comment by ShadowsAdi** [comment]
Hello,
Currently plugin does not support admin auth via steamid.

**Comment by fred0r** [comment]
oh - ok.
